### PR TITLE
GlyphSerializer rounding fix

### LINKED ISSUE #6525: WPF Characters render differently in XPS document and on screen ( VisualContainer ) in WPF Application
* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`) :  **Any ( 5.0 , 6.0 )**
* Windows version: (`winver`)   **Any**
* Does the bug reproduce also in WPF for .NET Framework 4.8?:   **Yes**
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? If yes, please file the issue via the instructions [here](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019)   **No**
* Security issues and bugs should be reported privately, learn more via our [responsible disclosure guidelines](https://github.com/dotnet/wpf/blob/main/README.md#reporting-security-issues-and-security-bugs).

 

Output on Screen : 
on-screen

Output in XPS File :
on-xps

 
 **Problem description:**
When we render WPF characters as an XPS document, the output is incorrectly rendered as compared to that on the screen, thus affecting the visual fidelity of the applications.

 **Actual behavior:** 
Incorrectly sized outputs when XPS document is created.
 
 **Expected behavior:**
 The output on both screen and XPS document is similar.

### LINKED ISSUE #7499: Printing from WPF is leaving random small spaces in the text when using Arial or Calibri fonts
### Description

When printing in WPF, the graphics engine is inserting small spaces within words.  For instance, the French word 'fonctions' is printed either as 'fonction s' or 'fo nctions' depending on where the word appears within the other text.

### Reproduction Steps

```c#
public void PrintItAll()
        {
            var printDialog = new PrintDialog();
            if (printDialog.ShowDialog() == true)
            {
                var fontFamily = new FontFamily("Arial");
                var printme = new TextBlock {
                    FontSize = 11, FontFamily = fontFamily, Width = 800, TextWrapping = TextWrapping.Wrap,
                    Text = "L'autre personne était incapable de prendre soin des enfants en raison d'une déficience des fonctions physiques ou mentales qui l'a obligée, durant une période d'au moins deux semaines, à garder le lit, à se déplacer en fauteuil roulant ou à recevoir des soins dans un hôpital ou un établissement semblable. Joignez un certificat du médecin traitant qui confirme la nature et la durée de la déficience."
                };
                printDialog.PrintVisual(printme, "Test Print");
            }
        }
```

Reproduction repository: https://github.com/campeters/Wpf-Print-Font-Issue

### Expected behavior

The text should print correctly without extra spaces.

### Actual behavior

The following file shows a space between 'fonction' and the 's'.  It should be a single french word 'fonctions'

[Test Print.pdf](https://github.com/dotnet/wpf/files/10582445/Test.Print.pdf)

### Regression?

This code works correctly in dot net framework and it also seems to work correctly in .net 5.

### Known Workarounds

None.

### Impact

This bug impacts the quality of PDF and print files generated from WPF programs using the 'Arial' or 'Calibri' fonts.  Some fonts work correctly.  However, the filing of some government forms require that only 'Arial' be used.

### Configuration

This bug occurs in .net 6, confirmed in 6.0.11 and 6.0.13 and .net 7. It does not appear to be specific to the configuration.  It happens on Windows 10 and Windows 11.

The exact same code works correctly in .net framework 4.8.1

### Other information

_No response_

### PR DESCRIPTION
**Pull request by miloush**
Fixes #7499

Related: #6295

## Description

Previous rounding strategy
1. did not calculate the error according to XPS specification
2. updated error with shaping value when font value is used by the client

The PR fixes 1. by keeping track of total advance width (desired and rounded) and 2. by using the font advance width when no value is output to XPS.

## Customer Impact

Customers not taking this fix will see either gaps or overlapped characters when producing XPS with text. See #7499 for an example.

## Regression

Yes. Introduced by #6295 trying to fix #6525. This PR addresses both issues.

## Testing

Tested manually using repro projects for #6525 and #7499.

image

## Risk

Same risks as with #6295. This PR changes relative positioning of glyphs in a GlyphRun to match the bounding box, so it should not cause reflow of documents.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/wpf/pull/7545)

### CODE REVIEW

**Comment by miloush** [comment]
@campeters try this

**Comment by campeters** [comment]
This works for my test cases.  Thank you so much!

**Review by campeters — APPROVED** [review]
My only comment is when initializing the doubles should we set them to 0.0?

Either for style convention or prevent the compiler from needing to do the implicit conversion from int to double?

**Comment by miloush** [comment]
> I was able to get the same result using only a single double to aggregate the error 

Yes that was the approach of the original fix. However, the XPS specification puts a hard requirement on keeping the total and subtracting the sum of advance to avoid error accumulation.

**Comment by campeters** [comment]
@dipeshmsft @singhashish-wpf - Thanks for the help on this.  Would you be able to share any details on when we will see this fix in a public release?

**Comment by dipeshmsft** [comment]
Thanks @miloush . Looks good to me. We will take it up for the next test pass. As far as I remember, we may need to make some changes in the test code as well. I am on it.

**Comment by campeters** [comment]
> Thanks @miloush . Looks good to me. We will take it up for the next test pass. As far as I remember, we may need to make some changes in the test code as well. I am on it.

@dipeshmsft - Is this something that will be merged into a dotnet 6 maintenance release as well?

**Comment by wstaelens** [comment]
> > Thanks @miloush . Looks good to me. We will take it up for the next test pass. As far as I remember, we may need to make some changes in the test code as well. I am on it.
> 
> @dipeshmsft - Is this something that will be merged into a dotnet 6 maintenance release as well?

yes @dipeshmsft  , how can we get this fix? [our customers experience](https://github.com/dotnet/wpf/issues/7499#issuecomment-1475819399) also this XPS issue.

**Comment by dipeshmsft** [comment]
@campeters @wstaelens, we will be taking this PR for the next round of test pass and once that is complete, we will take this PR for upcoming .NET servicing releases.

**Comment by wstaelens** [comment]
> @campeters @wstaelens, we will be taking this PR for the next round of test pass and once that is complete, we will take this PR for upcoming .NET servicing releases.

@dipeshmsft  great! just so that I can inform our customers: are we talking about days, weeks or months?

**Comment by dipeshmsft** [comment]
@wstaelens, I will get back on this, once the test pass is complete.

**Comment by wstaelens** [comment]
> @wstaelens, I will get back on this, once the test pass is complete.

will this be in regular Windows Updates for customers or OOB?

**Comment by dipeshmsft** [comment]
The fix causing regression was not included in .NET Framework, so it will not be present in either. This fix will be shipped with .NET SDK servicing release.

**Comment by wstaelens** [comment]
@singhashish-wpf I guess this will be backported to 6.0 also, as this is Long term release (and our products affected are not yet on .net 7)

**Pull request merged**
