### PR TITLE
Small change to documentation to test PR builds

### PR DESCRIPTION
**Pull request by vatsan-madhavan**
Small change to documentation to test PR builds

### CODE REVIEW

**Comment by vatsan-madhavan** [comment]
Anyone know how msftbot check was added and how to remove it?

**Comment by vatsan-madhavan** [comment]
@grubioe ?

**Comment by grubioe** [comment]
I don't see any related rule for this on the bot Admin UI.  I'll email the fabric team.

**Comment by vatsan-madhavan** [comment]
@grubioe just trying to eliminate potential causes for https://github.com/dotnet/arcade/issues/2847. That check seemed new and I hadn’t seen it before or in other repos...

**Pull request closed without merging**
