### PR TITLE
Hit testing by geometry fails if more than one matrix trasformation is applied to a geometry.

### PR DESCRIPTION
**Pull request by Simon-IT**
This is related to my issue [642](https://github.com/dotnet/wpf/issues/642).  In the hit testing by geometry algotithm, the order in which the transformations are crosses is wrong. In the issue [642](https://github.com/dotnet/wpf/issues/642) there is a project to test in very simple manner the problem.

### CODE REVIEW

**Comment by Simon-IT** [comment]
Hi, any news about my pull request ?

**Comment by weltkante** [comment]
The issue is classified as 'future' so there is probably nobody looking at it, right now 3.0 release has priority. Maybe get someone looking at the issue first (maybe inclusion in 5.0 is still realistic), looking at the github UI nobody is tracking the PR.

**Comment by Simon-IT** [comment]
@vatsan-madhavan When is the 5.0 scheduled for ? We really need it for our WPF CAD product. Isn't really possible for 3.1 ?

**Comment by vatsan-madhavan** [comment]
> @vatsan-madhavan Vatsan Madhavan FTE When is the 5.0 scheduled for ? We really need it for our WPF CAD product. Isn't really possible for 3.1 ?

5.0 won't release until later in '20. @grubioe is looking into the best way to get this into 3.1 - look for an update from him soon.

**Comment by rladuca** [comment]
@Simon-IT Setting NO MERGE until we get 3.1 approval, then we can move forward.

**Comment by rladuca** [comment]
Moving this back to 5.0 since it is based on master, #2103 is the 3.1 port.

**Pull request merged**
