### PR TITLE
Remove AssemblyFilter dead code as APTCA is not supported

### PR DESCRIPTION
**Pull request by h3xds1nz**
## Description

Removes `AssemblyFilter` class that is just a compiled dead code. APTCA is not supported on .NET Core the same way CAS and XBAP is not supported. This is on `NetFX` initiated via `PresentationAppDomainManager` that has a hook on new `AppDomain` creation. The type has been rendered obsolete the same time app domains ceased to exist even if it was initiated.

## Customer Impact

Decreased size of assemblies, better code quality of codebase for developers.

## Regression

No.

## Testing

Local build.

## Risk

I believe there is none, this code is unused on .NET Core.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/wpf/pull/9863)

### CODE REVIEW

**Comment by h3xds1nz** [comment]
Resolved merge conflicts 02

**Review by siagupta0202 — APPROVED** [review]

**Comment by siagupta0202** [comment]
@h3xds1nz Thank you for your contribution

**Comment by h3xds1nz** [comment]
@siagupta0202 Thank you.

**Pull request merged**
