### PR TITLE
Make build.sh executable

### PR DESCRIPTION
**Pull request by hughbe**

### CODE REVIEW

**Comment by hughbe** [comment]
Lets us run `./build.sh` from the prompt

**Comment by stevenbrix** [comment]
@hughbe i don't see any changes to the file, what exactly was changed?

**Comment by hughbe** [comment]
All that’s changed is the flags of the file. Previously it was not executable but I ran `chmod +x` allowing it to be executable. There’s no change in the content of the file

**Comment by stevenbrix** [comment]
Awesome, thanks @hughbe!

**Pull request merged**
