### PR TITLE
Setting default TargetPlatformVersion

### PR DESCRIPTION
**Pull request by sfoslund**
Fixes dotnet/sdk#11233

cc @wli3

### CODE REVIEW

**Comment by vatsan-madhavan** [comment]
Does this affect anything besides CsWinRT scenarios ?

**Comment by wli3** [comment]
This change is more about future net5.0, net6.0 work. Detail is in there https://github.com/dotnet/sdk/issues/11233

**Comment by vatsan-madhavan** [comment]
I’m asked after having looked there. The description there is a bit obscure but I found a link to https://github.com/dotnet/sdk/issues/11556, which seemed suggestive.

**Comment by wli3** [comment]
@vatsan-madhavan Daniel [commented](https://github.com/dotnet/sdk/issues/11233#issuecomment-649583363).

@vatsan-madhavan @ryalanms, is there anything else you need to move forward?

**Comment by vatsan-madhavan** [comment]
I’m all good.

**Comment by dsplaisted** [comment]
My opinion is that we should put this type of Windows-specific logic (as well as the logic to reference CSWinRT targeting packs, etc.) in dotnet/sdk, and the targets in dotnet/wpf should be the ones that are specifically for WPF.

I don't want to hold anything up if this way allows us to make progress faster, but that's where I'd like to end up.

@wli3 @sfoslund @vatsan-madhavan

**Comment by wli3** [comment]
Lets' keep this going. We don't have much time left. We could do the shuffling in RC or post 5.0

**Comment by sfoslund** [comment]
@vatsan-madhavan @ryalanms is there anything else that needs to be done here?

**Comment by ryalanms** [comment]
> Lets' keep this going. We don't have much time left. We could do the shuffling in RC or post 5.0

@wli3: Can you make sure to track this refactoring work in another issue?  Thanks.

**Comment by sfoslund** [comment]
I don't have merge access, but this should be ready to go. Thanks!

**Pull request merged**
