### PR TITLE
Use string.Equals over string.Compare in ContentType for improved performance

### PR DESCRIPTION
**Pull request by h3xds1nz**
## Description

Replaces two uses of `string.Compare` in `ContentType` which is used for equality check with `string.Equals`.

### Difference in the last character

| Method  | Mean [ns] | Error [ns] | StdDev [ns] | Code Size [B] | Allocated [B] |
|--------- |----------:|-----------:|------------:|--------------:|--------------:|
| Original | 36.525 ns |  0.7577 ns |   0.7781 ns |         446 B |             - |
| PR_EDIT  |  4.873 ns |  0.0175 ns |   0.0155 ns |         467 B |             - |

### Difference in 5th character

| Method   |  Mean [ns] | Error [ns] | StdDev [ns] | Code Size [B] | Allocated [B] |
|--------- |----------:|-----------:|------------:|--------------:|--------------:|
| Original |   4.627 ns |  0.0493 ns |   0.0437 ns |         446 B |             - |
| PR_EDIT  |  2.668 ns |  0.0138 ns |   0.0129 ns |         467 B |             - |

### Benchmark source strings
```csharp
//First invocation (last char is different)
return string.Compare("someveryrandomstringthatwillonlydifferintheveryendwewillmakesureofit0",
"someveryrandomstringthatwillonlydifferintheveryendwewillmakesureofit1", 
StringComparison.OrdinalIgnoreCase) == 0;
return string.Equals("someveryrandomstringthatwillonlydifferintheveryendwewillmakesureofit0",
"someveryrandomstringthatwillonlydifferintheveryendwewillmakesureofit1", 
StringComparison.OrdinalIgnoreCase);

//Second invocation (5th char is different)
return string.Compare("some0veryrandomstringthatwillonlydifferintheveryendwewillmakesureofit0",
"some1veryrandomstringthatwillonlydifferintheveryendwewillmakesureofit1", 
StringComparison.OrdinalIgnoreCase) == 0;
return string.Equals("some0veryrandomstringthatwillonlydifferintheveryendwewillmakesureofit0",
"some1veryrandomstringthatwillonlydifferintheveryendwewillmakesureofit1", 
StringComparison.OrdinalIgnoreCase);
```

## Customer Impact

Improved performance.

## Regression

No.

## Testing

Local build.

## Risk

None, you can't ruin anything with this swap.

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/wpf/pull/9724)

### CODE REVIEW

**Comment by h3xds1nz** [comment]
CI failure caused by #9632 requesting `System.Drawing.Common` from .NET 8 (v8.0.8).

**Comment by lindexi** [comment]
Reference: https://github.com/dotnet/wpf/pull/7836

I forgot about the subsequent optimization...

**Comment by h3xds1nz** [comment]
Now it shall be complete haha.

**Comment by lindexi** [comment]
Good job

**Comment by siagupta0202** [comment]
LGTM

**Review by siagupta0202 — APPROVED** [review]

**Comment by harshit7962** [comment]
@h3xds1nz Thank you for your contributions.

**Comment by h3xds1nz** [comment]
@harshit7962 Thank you for including them.

**Pull request merged**
