### PR TITLE
Remove internal Pair type in favor of generic tuples

### PR DESCRIPTION
**Pull request by h3xds1nz**
## Description

The internal `Pair` type is not really used anymore and is pretty much obsolete given we have both class and value generic tuples. Since is it only used in one case these days, we can avoid the value boxing here as well by migrating to generic tuple.

### Before / after:

| Method   | bool | version | Mean [ns] | Error [ns] | StdDev [ns] | Gen0   | Code Size [B] | Allocated [B] |
|--------- |----------------------- |-------- |----------:|-----------:|------------:|-------:|--------------:|--------------:|
| Original | True     | 123456  | 10.656 ns |  0.1693 ns |   0.1663 ns | 0.0072 |         410 B |         120 B |
| PR_EDIT | True     | 123456  |  6.774 ns |  0.1583 ns |   0.1945 ns | 0.0053 |         275 B |          88 B |

(Yes, we could have saved additional 16 bytes of overhead by using generic Action callback and not using the arg on `BeginInvoke` but that's a cleanup for another day, if it even evens out the generic construction overhead)

## Customer Impact

Slightly improved performance, decreased allocations upon invocation.

## Regression

No.

## Testing

Local build.

## Risk

Extremely low, just a type swap.

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/wpf/pull/9916)

### CODE REVIEW

**Review by dipeshmsft — APPROVED** [review]

**Review by himgoyalmicro — APPROVED** [review]

**Comment by himgoyalmicro** [comment]
@h3xds1nz we have reviewed this PR. Can you please resolve the merge conflict ?

**Comment by h3xds1nz** [comment]
@himgoyalmicro Done

**Review by himgoyalmicro — APPROVED** [review]

**Comment by himgoyalmicro** [comment]
Thank you @h3xds1nz for your contribution 😄

**Comment by h3xds1nz** [comment]
@himgoyalmicro Thank you :)

**Pull request merged**
