### PR TITLE
Remove unused item metadata after copy/paste in Visual Studio

### LINKED ISSUE #5461: Copy/paste in Visual Studio modifies project when using item globbing
**Problem description:**
 Visual Studio modifies the csproj when copy/pasting a xaml file.

This is not a critical bug because it's just reapplying the default metadata to the new item but it's annoying to have to revert changes to the csproj every time you copy/paste.

 **Actual behavior:**
Visual Studio modifies the csproj by adding this:
```
<ItemGroup>
  <Page Update="MainWindow - Copy.xaml">
    <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
    <SubType>Designer</SubType>
  </Page>
</ItemGroup>
```
 
 **Expected behavior:**
Visual Studio shouldn't modify the csproj.
 
 **Minimal repro:**
1. Create a new WPF in Visual Studio.
2. Copy/Paste MainWindow.xaml
3. Look for modifications in the csproj.

**Solution**
I already have a fix locally for removing \<XamlRuntime\> but it looks like \<SubType\> is added by Visual Studio so the fix is probably not going to be in this repo.

I'll send a PR for fixing \<XamlRuntime\> shortly.

### PR DESCRIPTION
**Pull request by ThomasGoulet73**
Fixes #5461

## Description
Removes unused item metadata that are automatically added to the project after copy/pasting a xaml file in Visual Studio.

## Customer Impact
None.

## Regression
No.

## Testing
Tested locally by modifying my installed SDK to apply the changes in this PR. It fixed the addition of `<XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>` on copy/paste.

## Risk
This PR will add `<Generator>MSBuild:Compile</Generator>` and `<XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>` to any `Page` or `ApplicationDefinition` item even if globbing is disabled or if they are added manually.

### CODE REVIEW

**Comment by vishalmsft** [comment]
@ThomasGoulet73 Thank you for providing the fix. 
Partially the risk portion can be mitigated, if ItemDefinitionGroup is also put under the condition 
`<ItemDefinitionGroup Condition=" '$(_EnableWindowsDesktopGlobbing)' == 'true' ">`

The second portion, where it adds those attributes to any ApplicationDefinition \ Page, need to learn more about implication of that. 

The SubType gets removed, if adding following attribute to ItemDefinitionGroup. Not sure, why this can be wrong or right. 
`
   <SubType>Designer</SubType>
`

**Comment by ThomasGoulet73** [comment]
@vishalmsft I added `<SubType>Designer</SubType>` and `_EnableWindowsDesktopGlobbing` condition. I did some testing and I think adding `<SubType>Designer</SubType>` is fine. I looked at other XAML frameworks and I found out that Uno Platform and Avalonia adds it:
https://github.com/unoplatform/uno/blob/master/src/SolutionTemplate/UnoSolutionTemplate/Shared/UnoQuickStart.Shared.projitems#L45
https://github.com/AvaloniaUI/Avalonia/blob/master/packages/Avalonia/AvaloniaBuildTasks.props#L8

**Comment by vishalmsft** [comment]
@ThomasGoulet73 Thank you references from other platforms. This helps expect no side-effects.

**Comment by vishalmsft** [comment]
This has been queued for test pass. Tests will be mainly about build of the Sample WPF application.

**Review by singhashish-wpf — APPROVED** [review]

**Pull request merged**
