### PR TITLE
Consume intellisense from nuget

### PR DESCRIPTION
**Pull request by singhashish-wpf**
Consume intellisense from Nuget feed.

### CODE REVIEW

**Comment by singhashish-wpf** [comment]
@RussKie The intellisense xml files are getting generated, just wanted to confirm on the path, should it be till windowsdesktop only or IntellisenseFiles as it is in the PR?
image

**Comment by RussKie** [comment]
The intellisense files you're interested in are in the windowsdesktop folder. https://github.com/dotnet/winforms/blob/main/eng/packageContent.targets#L6

**Review by RussKie — COMMENTED** [review]
LGTM.

There's a possibility of a race condition with `GetDocFiles` target, see https://github.com/dotnet/winforms/issues/6928 for more info.

**Review by dipeshmsft — APPROVED** [review]

**Pull request merged**
