### PR TITLE
Remove FriendAccessAllowedAttribute usage

### PR DESCRIPTION
**Pull request by ThomasGoulet73**
## Description
Remove FriendAccessAllowedAttribute usage since it is not enforced in .Net Core. FriendAccessAllowedAttribute is an undocumented and non-public attribute which is not supported anymore. To use `FriendAccessAllowedAttribute`, when supported, you need to set [InternalsVisibleToAttribute.AllInternalsVisible](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.internalsvisibletoattribute.allinternalsvisible) to false, which is never set in this repo.

There are modifications to generated files in `src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Generated` but these files are generated from [Elements.cs](https://github.com/dotnet/wpf/pull/6561/files#diff-cafc35f65c4ad3fe1ce32cde276636fb77ba8c17fd1344a3371679dc1ad9137f) which is not runnable in this repo right now (dotnet/wpf#6135) but it should be fine because once we can run MilCodeGen, there shouldn't be any diffs.

## Customer Impact
None.

## Regression
No.

## Testing
Local build + CI.

## Risk
Low.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/wpf/pull/6561)

### CODE REVIEW

**Comment by ThomasGoulet73** [comment]
I rebased to fix the conflicts.

**Comment by pchaurasia14** [comment]
Thanks @ThomasGoulet73! We'll consider this PR for our upcoming CTPs.

**Comment by ThomasGoulet73** [comment]
I rebased to fix the conflicts.

**Comment by lindexi** [comment]
> I rebased to fix the conflicts.

Now, this branch has conflicts

**Comment by ThomasGoulet73** [comment]
I rebased to fix the conflicts.

Thanks for the ping @lindexi.

**Comment by JeremyKuhne** [comment]
https://github.com/dotnet/runtime/issues/10707 has some more details on this attribute.

**Review by JeremyKuhne — APPROVED** [review]
@pchaurasia14 This would be good to get in.

**Review by dipeshmsft — APPROVED** [review]

**Comment by h3xds1nz** [comment]
Awesome! Those replacements from Thomas will clear out so much clutter.

**Pull request merged**
