### PR TITLE
ToolTip closes immediately in high DPI

### LINKED ISSUE #6220: Tooltip flicker in Ribbon Elements that are inside menu/dropdown
* .NET Core Version: 6.0.101
* Windows version: 21H1 OS Build : 19043.1526
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No

 
 
 **Problem description:**
 In .NET6 if you have a tooltip on a combobox/menu item it flickers and can't be read by user ( see picture https://imgur.com/a/RxFvAPP )
 **Actual behavior:** 
 Tooltip shows for just a few milliseconds on the screen and closes itself.
 **Expected behavior:**
 Tooltip does not close itself unless user moves the mouse
 **Minimal repro:**
https://github.com/SebiCiuca/RibbonToolTipFlicker

Steps to reproduce:
Open app .NET 5 - all tooltips for RibbonButton/RibbonMenuItem/RibbonGallery can be read by user ( they do not close unless move move)
Open app .NET 6 - tooltip from RibbonMenuItem/RibbonGallery can't be read by user they close in a matter of milliseconds. RibbonButton tooltip still works

### PR DESCRIPTION
**Pull request by SamBent**
Fixes #6220

## Description

In high DPI environment, most tooltips opened by the mouse close immediately.

This is because the SafeArea uses unscaled coordinates, while the current mouse point uses scaled coordinates.  In high DPI, these are different, leading to false negatives from the containment test "is the mouse within the SafeArea".

Fixed by using unscaled coordinates for the mouse point.  (And incidentally improving the perf by avoiding a lot of unnecessary transformations into, and out of, scaled coordinates.)

## Customer Impact

Make ToolTips great again (in high DPI).

## Regression

Regression in PR #5931.

## Testing

Tested by hand, but thoroughly, in .NET 4.8.1.  The automated tests don't cover high DPI, unless you explicitly run them on a machine whose primary monitor is high DPI.

This is a straightforward port of the .NET Fx fix, but should be tested in .NET Core anyway.

### CODE REVIEW

**Comment by barnum1** [comment]
Is there an estimated date for a version of .NET with a fix for this?
It's very awkward to explain to our users why tooltips do not work in our application.
Thanks.

**Comment by singhashish-wpf** [comment]
We are trying to push this to 6.0.5; may servicing release. Will keep you posted.

**Comment by lindexi** [comment]
I picked this PR to application and I tested the app for a week. This issue has been fixed and no new issues have been introduced.

**Comment by AlquistArj** [comment]
I'm also seeing the disappearing Tooltips in my WPF apps (using various versions of .NET from 4 up to 4.8). These have worked for years but stopped recently for some reason. Tooltips continue to work in Winforms and in WPF apps built with .NET5/6.

**Comment by barnum1** [comment]
> We are trying to push this to 6.0.5; may servicing release. Will keep you posted.

Hi, when is the estimated date for 6.0.5 release?

**Comment by barnum1** [comment]
@singhashish-wpf 
Could you please give us an estimated date of 6.0.5 release?
It is very difficult for us to explain this malfunction of our application to our users.
(We have no way to pull a PR and build a version ourselves.)

**Comment by singhashish-wpf** [comment]
You can expect it to be out by tomorrow PST.

> @singhashish-wpf Ashish Singh FTE Could you please give us an estimated date of 6.0.5 release? It is very difficult for us to explain this malfunction of our application to our users. (We have no way to pull a PR and build a version ourselves.)

**Pull request merged**
