### PR TITLE
DWriteForwarder in C#

### PR DESCRIPTION
**Pull request by kant2002**
Different approach to DWriteForwarder refactor

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/wpf/pull/6587)

### CODE REVIEW

**Comment by AaronRobinsonMSFT** [comment]
@kant2002 What was the thought process here? Is this using a COM object instead of the [C++/CLI library](https://github.com/dotnet/wpf/tree/main/src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder)?

**Comment by kant2002** [comment]
Here I concentrate on smallest possible change which move C++ code to C# code. IiRC this is duplication of same C++ code.

more of the check, if Any changes would be accepted at all

**Comment by kant2002** [comment]
Just so you know. I have branch where I finish whole portion process

**Comment by ThomasGoulet73** [comment]
I have open PRs related to porting DirectWriteForwarder to C# which IMO are ready for review and are good first steps at starting the port.

@AaronRobinsonMSFT: If it's ok with you, I would love to have your review/opinion on my PRs since your part of the .Net interop team (IIRC): #6171 and #6260

**Comment by AaronRobinsonMSFT** [comment]
@ThomasGoulet73 Looks like you got a good start on this. @kant2002 Any concerns with moving this conversation over to https://github.com/dotnet/wpf/pull/6171?

**Comment by ThomasGoulet73** [comment]
@kant2002 Since my PR dotnet/wpf#6171 was merged, I believe this PR can be closed. `DWriteFactory.Instance.GetSystemFontCollection()` was moved to managed so I don't believe this PR has any value anymore, is it okay to close it ?

**Pull request closed without merging**
