### PR TITLE
Removing vestigial files

### LINKED ISSUE #1797: Cleanup vestigial files brought back via incorrect merge conflict resolution
During snaps into Release/* branches, some incorrect conflict resolution revived previously deleted files.  These are not building and do not affect the product, but should be cleaned up in master.

Files to be cleaned are below:

```
Microsoft.DotNet.Wpf\src\WindowsBase\System\Security\Permissions\WebBrowserPermission.cs                    13,852 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\WindowsBase\System\Security\Permissions\MediaPermission.cs                         23,310 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\WindowsBase\MS\Internal\Permissions\UserInitiatedRoutedEventPermissionAttribute.cs  1,375 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\WindowsBase\MS\Internal\Permissions\UserInitiatedRoutedEventPermission.cs           1,348 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\WindowsBase\MS\Internal\Permissions\RightsManagementPermission.cs                   1,997 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\WindowsBase\MS\Internal\Permissions\CompoundFileIOPermission.cs                     1,999 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\WindowsBase\MS\Internal\IO\Zip\ZipIOZip64EndOfCentralDirectoryLocatorBlock.cs      11,327 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\WindowsBase\MS\Internal\IO\Zip\ZipIOZip64EndOfCentralDirectoryBlock.cs             22,739 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\WindowsBase\MS\Internal\IO\Zip\ZipIOVersionNeededToExtract.cs                         588 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\WindowsBase\MS\Internal\IO\Zip\ZipIORawDataFileBlock.cs                             9,317 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\WindowsBase\MS\Internal\IO\Zip\ZipIOModeEnforcingStream.cs                         11,642 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\WindowsBase\MS\Internal\IO\Zip\ZipIOLocalFileHeader.cs                             15,676 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\WindowsBase\MS\Internal\IO\Zip\ZipIOLocalFileDataDescriptor.cs                     10,714 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\WindowsBase\MS\Internal\IO\Zip\ZipIOLocalFileBlock.cs                              39,351 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\WindowsBase\MS\Internal\IO\Zip\ZipIOFileItemStream.cs                              23,681 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\WindowsBase\MS\Internal\IO\Zip\ZipIOExtraFieldZip64Element.cs                      11,154 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\WindowsBase\MS\Internal\IO\Zip\ZipIOExtraFieldPaddingElement.cs                     6,585 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\WindowsBase\MS\Internal\IO\Zip\ZipIOExtraFieldElement.cs                            7,384 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\WindowsBase\MS\Internal\IO\Zip\ZipIOExtraField.cs                                  11,822 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\WindowsBase\MS\Internal\IO\Zip\ZipIOEndOfCentralDirectoryBlock.cs                  18,995 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\WindowsBase\MS\Internal\IO\Zip\ZipIOCentralDirectoryFileHeader.cs                  22,168 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\WindowsBase\MS\Internal\IO\Zip\ZipIOCentralDirectoryDigitalSignature.cs             4,390 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\WindowsBase\MS\Internal\IO\Zip\ZipIOCentralDirectoryBlock.cs                       25,412 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\WindowsBase\MS\Internal\IO\Zip\ZipIOBlockManager.cs                                54,651 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\WindowsBase\MS\Internal\IO\Zip\ZipFileInfoCollection.cs                             2,089 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\WindowsBase\MS\Internal\IO\Zip\ZipFileInfo.cs                                       6,416 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\WindowsBase\MS\Internal\IO\Zip\ZipArchive.cs                                       31,690 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\WindowsBase\MS\Internal\IO\Zip\WriteTimeStream.cs                                   5,094 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\WindowsBase\MS\Internal\IO\Zip\ProgressiveCrcCalculatingStream.cs                  12,028 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\WindowsBase\MS\Internal\IO\Zip\IZipIOBlock.cs                                       6,839 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\WindowsBase\MS\Internal\IO\Zip\DeflateOptionEnum.cs                                 1,250 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\WindowsBase\MS\Internal\IO\Zip\Crc32.cs                                            11,730 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\WindowsBase\MS\Internal\IO\Zip\CompressionMethodEnum.cs                               805 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\WindowsBase\MS\Internal\IO\Packaging\streamingZipPartStream.cs                     13,423 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\WindowsBase\MS\Internal\IO\Packaging\PieceNameHelper.cs                            17,487 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\WindowsBase\MS\Internal\IO\Packaging\CompressStream.cs                             34,448 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\Shared\MS\Internal\Permissions\InternalPermissions.cs                               6,021 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\PresentationFramework\System\Windows\Interop\DocobjHost.cs                         67,438 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\PresentationFramework\MS\Internal\Utility\SponsorHelper.cs                          3,401 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\PresentationFramework\MS\Internal\permissions\UserInitiatedNavigationPermission.cs  1,813 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\PresentationFramework\MS\Internal\AppModel\IBrowserCallbackServices.cs             14,047 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\PresentationCore\System\Windows\Input\Command\ICommand.cs                             327 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\PresentationCore\MS\internal\ConstrainedDataObject.cs                              13,265 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\PresentationCore\README.md                                                            149 9/6/2019 10:23:48 AM
Microsoft.DotNet.Wpf\src\PresentationBuildTasks\Microsoft\Build\Tasks\Windows\review.htm                    57,276 9/6/2019 10:23:48 AM

```

### PR DESCRIPTION
**Pull request by rladuca**
Fixes #1797

### CODE REVIEW

**Comment by vatsan-madhavan** [comment]
For many of these files, you can do this to replay the old commits and retain history correctly: 

`git cherry-pick 08128b97bedfa40030d30db64dce7d5ea0924fc9 cc893476f2b80b5e7f0e960d59d21b45162c2b1b c08183de04139f578530f32bcb4e70b84138b646 ac9d1b7a6b0ee7c44fd2875a1174b820b394061`

**Comment by rladuca** [comment]
> For many of these files, you can do this to replay the old commits and retain history correctly:
> 
> `git cherry-pick 08128b97bedfa40030d30db64dce7d5ea0924fc9 cc893476f2b80b5e7f0e960d59d21b45162c2b1b c08183de04139f578530f32bcb4e70b84138b646 ac9d1b7a6b0ee7c44fd2875a1174b820b394061`

Let me see what sort of set of changes that gives me.  Should be fine I would think.

**Comment by rladuca** [comment]
> > For many of these files, you can do this to replay the old commits and retain history correctly:
> > `git cherry-pick 08128b97bedfa40030d30db64dce7d5ea0924fc9 cc893476f2b80b5e7f0e960d59d21b45162c2b1b c08183de04139f578530f32bcb4e70b84138b646 ac9d1b7a6b0ee7c44fd2875a1174b820b394061`
> 
> Let me see what sort of set of changes that gives me. Should be fine I would think.

Some of these commits contains conflicts.  So no matter what, you're going to have a resolution commit sitting on the top.  I think it makes more sense just to delete them directly at that point.  Unless I am missing something.

**Comment by vatsan-madhavan** [comment]
It should fixup everything except these:

```
Microsoft.DotNet.Wpf\src\WindowsBase\System\Security\Permissions\WebBrowserPermission.cs
Microsoft.DotNet.Wpf\src\WindowsBase\System\Security\Permissions\MediaPermission.cs                         
Microsoft.DotNet.Wpf\src\WindowsBase\MS\Internal\Permissions\UserInitiatedRoutedEventPermissionAttribute.cs  
Microsoft.DotNet.Wpf\src\WindowsBase\MS\Internal\Permissions\UserInitiatedRoutedEventPermission.cs           
Microsoft.DotNet.Wpf\src\WindowsBase\MS\Internal\Permissions\RightsManagementPermission.cs                   
Microsoft.DotNet.Wpf\src\WindowsBase\MS\Internal\Permissions\CompoundFileIOPermission.cs                     
Microsoft.DotNet.Wpf\src\Shared\MS\Internal\Permissions\InternalPermissions.cs                               
Microsoft.DotNet.Wpf\src\PresentationFramework\System\Windows\Interop\DocobjHost.cs                         
Microsoft.DotNet.Wpf\src\PresentationFramework\MS\Internal\Utility\SponsorHelper.cs                          
Microsoft.DotNet.Wpf\src\PresentationFramework\MS\Internal\permissions\UserInitiatedNavigationPermission.cs  
Microsoft.DotNet.Wpf\src\PresentationFramework\MS\Internal\AppModel\IBrowserCallbackServices.cs            
Microsoft.DotNet.Wpf\src\PresentationCore\System\Windows\Input\Command\ICommand.cs                             
Microsoft.DotNet.Wpf\src\PresentationCore\MS\internal\ConstrainedDataObject.cs                             
Microsoft.DotNet.Wpf\src\PresentationCore\README.md                                                            
Microsoft.DotNet.Wpf\src\PresentationBuildTasks\Microsoft\Build\Tasks\Windows\review.htm                    
```

**Comment by vatsan-madhavan** [comment]
>  So no matter what, you're going to have a resolution commit sitting on the top.

Not during cherry-pick - give it a try. Or check out `dev/vatsan/replay-08128b97 `which has cherry-picked everything I've listed (including `ac9d1b7a6b0ee7c44fd2875a1174b820b3940619`)

**Comment by rladuca** [comment]
> > So no matter what, you're going to have a resolution commit sitting on the top.
> 
> Not during cherry-pick - give it a try. Or check out `dev/vatsan/replay-08128b97 `which has cherry-picked everything I've listed (including `ac9d1b7a6b0ee7c44fd2875a1174b820b3940619`)

I see, but I am still unsure why we would want to do this.  You now have commits that state they do various things that they don't do.  Looking at the commit diffs in your branch, most of them are blank anyway (save for the zip files).  If you just merge without squashing that seems very odd to me.  If you're squashing anyway, what's the difference between a single commit with the deletes and this?

**Comment by vatsan-madhavan** [comment]
> I see, but I am still unsure why we would want to do this. You now have commits that state they do various things that they don't do. Looking at the commit diffs in your branch, most of them are blank anyway (save for the zip files). If you just merge without squashing that seems very odd to me. If you're squashing anyway, what's the difference between a single commit with the deletes and this?

Why not just go back and amend the bad commit?

**Comment by rladuca** [comment]
> > I see, but I am still unsure why we would want to do this. You now have commits that state they do various things that they don't do. Looking at the commit diffs in your branch, most of them are blank anyway (save for the zip files). If you just merge without squashing that seems very odd to me. If you're squashing anyway, what's the difference between a single commit with the deletes and this?
> 
> Why not just go back and amend the bad commit?

An amended commit changes its SHA.  I believe at that point you'd have to force push the branch in order to get it to the remote.

**Comment by weltkante** [comment]
please avoid a force push / rewriting history if possible at all, it breaks everyone currently working on the repository

**Comment by vatsan-madhavan** [comment]
> please avoid a force push / rewriting history if possible at all, it breaks everyone currently working on the repository

yeah, my mistake - it was a (very) bad idea :|

**Pull request merged**
