### PR TITLE
Use ArgumentNullException.ThrowIfNull in PresentationFramework

### PR DESCRIPTION
**Pull request by halgab**
## Description

Use ArgumentNullException.ThrowIfNull in PresentationFramework, as in #7181

## Regression

No

## Testing

CI

## Risk

Low: changes are mostly mechanic, using fixer CA1510

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/wpf/pull/8092)

### CODE REVIEW

**Review by lindexi — CHANGES_REQUESTED** [review]
Thank you @halgab

Could you fix the compile issues?

We can not use `ArgumentNullException.ThrowIfNull` in XmlnsDictionary.cs, because the PresentationBuildTasks.csproj use the XmlnsDictionary.cs. And the PresentationBuildTasks.csproj should target .NET Framework 4.7.2.

**Comment by halgab** [comment]
Thanks a lot for your help @lindexi. Having code in a mono-targeted project shared with a multi-targeted project sure is misleading! I'm sorting out this mess and will mark the PR as ready for review again when I'm done

**Comment by halgab** [comment]
It's ready now

**Comment by lindexi** [comment]
Awesome @halgab

**Comment by rchauhan18** [comment]
Thanks @halgab for the contribution.

**Pull request merged**
