### PR TITLE
Add WindowsBase, PresentationCore, PresentationFramework (+more) sources

### PR DESCRIPTION
**Pull request by vatsan-madhavan**
This PR adds sources for the following assemblies: 

- WindowsBase
- PresentationCore
- PresentationFramework
- DirectWriteForwarder
- ReachFramework
- System.Windows.Input.Manipulations
- UIAutomation
   - UIAutomationClient
   - UIAutomationClientSideProviders
   - UIAutomationProvider
   - UIAutomationTypes

/cc @dotnet/wpf-developers 
/cc @grubioe, @ryalanms , @rladuca, @stevenbrix , @amit-kabra , @fabiant3 , @miguep , @ojhad

### CODE REVIEW

**Comment by dotMorten** [comment]
WOOHOO

**Comment by amit-kabra** [comment]
Yes!

**Comment by fabiant3** [comment]
Way to go team!!

**Comment by rickbrew** [comment]
Best Pull Request of 2019 Award

https://www.youtube.com/watch?v=DSqNLA1pWxk

**Comment by mdtauk** [comment]
A step closer to being able to do some cool things with WPF control templates when running under WinUI 3.0 maybe.  Fluent design for controls to look comfortable alongside UWP XAML.

### Fluent.NormalColor.xaml

😄

**Comment by matijagrcic** [comment]
Amazing!

**Comment by merriemcgaw** [comment]
Awesome guys!! 🥇 🎆 🍾

**Comment by lindexi** [comment]
Congratulate !!!

**Comment by walterlv** [comment]
Excellent! WPF is closer and closer to fully open-source.

**Comment by h82258652** [comment]
Great! The best PR in 2019.

**Comment by vatsan-madhavan** [comment]
Folks might have missed this, but there was another (smaller) set shortly after: https://github.com/dotnet/wpf/pull/727

**Comment by thomasclaudiushuber** [comment]
Wow, happened much sooner than I expected it! **Congrats** to the whole team. Great and important milestone!

**Comment by AlexBorsody** [comment]
about time, great job.

**Comment by Murgio** [comment]
Love it, this is the single best thing that could possibly happen. 👏 👏

**Comment by schungx** [comment]
Now all we need is some nice gents to port it to Linux... 😆

**Comment by weltkante** [comment]
@schungx the most important part, the rendering engine, is still missing

**Comment by weltkante** [comment]
@lindexi other people can still port it, the MIT license should allow it - thats what @schungx was talking about - it's just that Microsoft won't do the work for you, and that they'll probably not include it into the main WPF github/nuget repository - but that doesn't prevent a working implementation

**Pull request merged**
