### PR TITLE
Clean up code in System.Xaml

### PR DESCRIPTION
**Pull request by thomasclaudiushuber**
This PR cleans up code in different files of System.Xaml.

Mainly
- expression bodied properties for one-line getters
- var where type is obvious from assignment
- nameof instead of string
- Use readonly auto properties where possible

### CODE REVIEW

**Comment by thomasclaudiushuber** [comment]
Ok, finally after some updates I got it building. I think I got the record for the most broken builds of a day. 🥇 

That this property of type Save**d**ContextType is not called Save**d**ContextType, but SaveContextType, broke the build a few times:

```public SavedContextType SaveContextType { get; }```

I think I'm going to change its name in another PR to Save**d**ContextType, but I'll wait with that until the rest of WPF is open source too.

**Comment by stevenbrix** [comment]
@thomasclaudiushuber are there roslyn analyzers for these sort of changes? And did you make these changes manually or through Visual Studio?

**Comment by thomasclaudiushuber** [comment]
Hi Steven,

no, there are no analyzers (I don't think there are), and yes, I made these changes in Visual Studio.

**Comment by stevenbrix** [comment]
cool, thanks! yeah we're working on trying to come up with guidelines on how contributors can make code cleanup changes in a reasonable way that reduces chances of human error and regressions.

I probably should've clarified a bit on what I meant by "inside Visual Studio", did you do them automatically or manually?

**Comment by dotMorten** [comment]
I do have a code analyzer that can identify all potential uses of nameof(...) (I used this for the 2nd WinForms PR that got merged: https://github.com/dotnet/winforms/pull/86)
I'd be happy to give it a go on this code base

**Comment by thomasclaudiushuber** [comment]
@stevenbrix I did all changes manually, with the eye of the tiger.  8-)

**Comment by miloush** [comment]
I would rather see a code style guidelines first before any such changes are merged in.

**Comment by thomasclaudiushuber** [comment]
@stevenbrix I close this one and we do stuff like this after 3.0 with the analyzers from @dotMorten and others.

**Pull request closed without merging**
