### PR TITLE
Add missing CoherentParentDependency=Microsoft.NETCore.App for Microsoft.Private.Winforms

### PR DESCRIPTION
**Pull request by vatsan-madhavan**
- Move `Microsoft.Private.Winforms` from `Product` to `Toolset` Dependency
 - Add `CoherentParentDependency=Microsoft.NETCore.App` 
- Note: Not adding a `CoherentParentDependency=Microsoft.NETCore.App` for `Microsoft.DotNet.Wpf.DncEng` - this is a cycle from dotnet-wpf-int => dotnet/wpf used for testing purposes only.

### CODE REVIEW

**Comment by zsd4yr** [comment]
You may want to run update-dependencies to be sure that the current version of winforms is satisfied by the new coherent parent dependency :)

**Comment by vatsan-madhavan** [comment]
> You may want to run update-dependencies to be sure that the current version of winforms is satisfied by the new coherent parent dependency :)

@zsd4yr it seems to take us back a few versions...

**Comment by mmitche** [comment]
> > You may want to run update-dependencies to be sure that the current version of winforms is satisfied by the new coherent parent dependency :)
> 
> @zsd4yr it seems to take us back a few versions...

Is that is the version that is currently referenced in core-setup?

**Comment by vatsan-madhavan** [comment]
> Is that is the version that is currently referenced in core-setup?

yes, it is.

**Pull request merged**
