### PR TITLE
Use ArgumentNullException.ThrowIfNull System.Windows.Controls.Ribbon and System.Windows.Input.Manipulations

### PR DESCRIPTION
**Pull request by halgab**
## Description

- Use `ArgumentNullException.ThrowIfNull` in System.Windows.Controls.Ribbon, as in #7181
- Remove internal method `Validations.CheckNotNull` and replace with `ArgumentNullException.ThrowIfNull` in System.Windows.Input.Manipulations

## Regression

No

## Testing

CI

## Risk

Low: the changes from the first commit are mostly mechanic, using fixer CA1510. The ones from the second commit are scarce

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/wpf/pull/8193)

### CODE REVIEW

**Comment by miloush** [comment]
I would expect to note that a public member of an internal class is removed.

LGTM.

**Comment by halgab** [comment]
> I would expect to note that a public member of an internal class is removed.

I've updated the PR description to be more explicit about this part.

**Comment by lindexi** [comment]
Awesome

**Comment by rchauhan18** [comment]
Thanks @halgab for your contribution.

**Pull request merged**
