### PR TITLE
Update SDK from Preview 6 to RC1, add workaround for TFM change, update Windows SDK

### PR DESCRIPTION
**Pull request by ryalanms**
WPF is building against an old version of the SDK.  Update the SDK to RC1, add workaround for TFM change, update the Windows SDK version, and fix new CA2200 errors (Rethrow to preserve stack details.) 

(There is an associated change in the internal repo.)

### CODE REVIEW

**Comment by vatsan-madhavan** [comment]
For some reason the build-pool that's being used doesn't seem to have Win10 18362 SDK. You might as well bump up the SDK to 10.0.19041.0

**Review by fabiant3 — APPROVED** [review]

**Comment by ryalanms** [comment]
Bumping the Windows SDK to 10.0.19041.0 resulted in a number of errors.  I will investigate this tomorrow.  Thanks.

**Comment by vatsan-madhavan** [comment]
Your failures don't seem related to Windows SDK. 

>##[error]C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(93,5): error MSB4184: (NETCORE_ENGINEERING_TELEMETRY=Restore) The expression "[Microsoft.Build.Utilities.ToolLocationHelper]::GetPlatformSDKLocation('', 10.0.18362.0)" cannot be evaluated. Parameter "targetPlatformIdentifier" cannot have zero length.

That looks like a known .NET 5 SDK bug - https://github.com/dotnet/msbuild/issues/5709

**Comment by ryalanms** [comment]
Thanks, @vatsan-madhavan.  @wil3 and @dsplaisted:  The bug says the fix is in RC1.  Is it also in master?  Thanks.

**Comment by dsplaisted** [comment]
Yes, it sounds like you probably need RC1

**Comment by ryalanms** [comment]
@mmitche:  Can you confirm that it is safe for WPF and WPF-int to move to RC1?  Thanks.

**Comment by ryalanms** [comment]
The repo builds locally with the VS Preview 2.0, but the build servers are still failing: 

>.dotnet\sdk\5.0.100-rc.1.20454.5\Sdks\Microsoft.NET.SDK\targets\Microsoft.PackageDependencyResolution.targets#L241
.dotnet\sdk\5.0.100-rc.1.20454.5\Sdks\Microsoft.NET.SDK\targets\Microsoft.PackageDependencyResolution.targets(241,5): error NETSDK1005: (NETCORE_ENGINEERING_TELEMETRY=Build) Assets file 'F:\workspace\_work\1\s\artifacts\obj\Microsoft.DotNet.Arcade.Wpf.Sdk.ArchNeutral\project.assets.json' doesn't have a target for 'netcoreapp5.0'. Ensure that restore has run and that you have included 'netcoreapp5.0' in the TargetFrameworks for your project.

**Comment by dpaoliello** [comment]
Please update `Documentation/wpf.vsconfig` with the new version of the Windows SDK being used.

**Pull request merged**
