### PR TITLE
Fix a few typos in comments

### PR DESCRIPTION
**Pull request by AndreyAkinshin**

### CODE REVIEW

**Comment by stevenbrix** [comment]
Hey Andrey, you caught us as we were transitioning over to a new CI build. You can ignore the failure for the `dotnet-wpf-github (to be deleted)` status check

**Comment by rladuca** [comment]
@AndreyAkinshin Please feel free to merge this.  If the CI build switchover is blocking you somehow, let us know.

Thanks again!

**Comment by karelz** [comment]
@rladuca only Write-access members can merge.
Is the "dotnet-wpf-github (to be deleted)" CI leg important? If not, we should Squash & Merge.

**Comment by rladuca** [comment]
@karelz Oops, momentary lapse of reason.

**Comment by karelz** [comment]
No worries, totally reasonable misunderstanding how GitHub workflow works, now you know 😃

**Pull request merged**
