### PR TITLE
[release/7.0] Enable in-build signing and do some clean-up

### PR DESCRIPTION
**Pull request by mmitche**
- Remove some unused variables
- Enable in-build signing on release branches

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/wpf/pull/7016)

### CODE REVIEW

**Comment by mmitche** [comment]
This will need fixes from https://github.com/dotnet/wpf/pull/7010

**Comment by mmitche** [comment]
@singhashish-wpf Any idea on these errors?

**Review by singhashish-wpf — APPROVED** [review]

**Comment by singhashish-wpf** [comment]
Removed DRT Running step from 7.0 to unblock this. The DRT step is failing coz of the pool updates and related things. Will check and add it later.

**Pull request merged**
