### PR TITLE
Add the property for MicrosoftWindowsDesktopSdkImported

### PR DESCRIPTION
**Pull request by wli3**
So SDK side of the change will not be blocked by WPF side of change
More info in https://github.com/dotnet/sdk/issues/12108

### CODE REVIEW

**Comment by wli3** [comment]
@ryalanms this is a simple marker to avoid double import. Could you approve that?

**Comment by wli3** [comment]
cc @dsplaisted

**Comment by vatsan-madhavan** [comment]
Will you have a similar marker in Sdk.targets as well?

**Comment by wli3** [comment]
This property is enough, we won't import both props and targets if it has the mark

**Comment by wli3** [comment]
And please help me merge it. I don't have the merge access

**Comment by wli3** [comment]
@vatsan-madhavan @ryalanms could you help me merge this change?

**Comment by vatsan-madhavan** [comment]
@ryalanms should take point here.

**Pull request merged**
