### PR TITLE
Removed declarative CAS permission attributes and comments

### PR DESCRIPTION
**Pull request by ojhad**
Part of Issue #241 
Another PR upcoming to complete the rest of the attribute removal

### CODE REVIEW

**Comment by vatsan-madhavan** [comment]
- DirectWriteForwarder continues to have these declarative permissions intact. 
- `MediaTrace.cs` in PresentationCore still has `SecurityCriticalAttribute` etc. that's left behind.

**Comment by vatsan-madhavan** [comment]
Pesentationcore, System.Xaml look good.

**Comment by vatsan-madhavan** [comment]
The changes look good. Definitely requires another round of changes to  complete the work, but I see no reason to block merging this.

**Comment by ojhad** [comment]
> Would you mind listing the types that are part of your candidate list for removal?

Talked offline, adding list here for posterity
[permtypelist.txt](https://github.com/dotnet/wpf/files/3304342/permtypelist.txt)

**Pull request merged**
