### PR TITLE
LOC CHECKIN | dotnet/wpf master | 20190131

### PR DESCRIPTION
**Pull request by v-zbsail**

### CODE REVIEW

**Comment by janbaltus** [comment]
Please wait with merge till 2/1. We neeed to update PR with fully localized xlf

**Comment by karelz** [comment]
@janbaltus marking as "NO MERGE" per your request

**Comment by janbaltus** [comment]
@karelz please merge now. PR is updated

**Comment by karelz** [comment]
"NO MERGE" removed, I let WPF team to review it & merge as appropriate.

**Comment by ryalanms** [comment]
@vatsan-madhavan, the change looks good, though we may amend the translations slightly based on the results of our internal analysis.  I don't have write access and cannot merge.

**Pull request merged**
