### PR TITLE
Remove VerifyWpfDllSet

### LINKED ISSUE #3322: Remove WpfDllVerifier checks from WPF
WPF has runtime checks to verify the correct versions of WPF assemblies are being loaded. It does so by validating that the DLLs are loaded from the same path. These checks were very useful when porting WPF to .NET Core, but WPF assembly load locations are varied for .NET 5 scenarios. The WpfDllVerifier class and uses of it should be removed for .NET 5.

    /// This class attempts to verify that core WPF binaries are all loaded from the same
    /// location.  Due to the fact that WPF can load binaries in different orders, this class
    /// needs to be called from all of the core managed binaries in static constructors of
    /// commonly used classes.
    /// 
    /// This can also be used to verify specific additional binaries as needed (say if they are
    /// optionally loaded).

    /// If the binaries fail to load from the same location an exception is thrown as we cannot 
    /// guarantee there won't be difficult to debug issues.

#11350
dotnet/runtime#38636

### PR DESCRIPTION
**Pull request by agocke**
Fixes #3322

### CODE REVIEW

**Comment by vatsan-madhavan** [comment]
Your build failures are unrelated to your PR. You may have to be patient until the team gets around to dealing with #2870

**Comment by agocke** [comment]
@vatsan-madhavan Is this ready to merge?

**Comment by agocke** [comment]
ping @vatsan-madhavan

**Comment by vatsan-madhavan** [comment]
/cc @rladuca

Recapping an internal email: I believe our discussion ended with the suggestion to retain the verifier them rather than remove it. Instead of checking consistency based on file-paths, the idea was to use a more flexible scheme, for e.g., a SHA, GUID or another unique ID, and factor in considerations like the presence of binaries from an other repo (dotnet-wpf-int) in the implementation, and also keep the implementation flexible enough to allow development in the inner-loop remain unconstrained.

I'll let the current team (already added as reviewers) take this PR forward how they see appropriate.  I'm happy to review additional changes as time permits (I'm on vacation for a few days - check my out-of-office message at work for details for those of you who have access 😉 ). This change looks like the right implementation if the goal were "removing the DLL verifier".

**Comment by agocke** [comment]
>  the idea was to use a more flexible scheme, for e.g., a SHA, GUID or another unique ID

This makes sense, it's basically what Roslyn does to make sure that the compiler client and server are in-sync.

But I think we should take a weighted approach to problem solving here: without any change, there's a 100% probability that single-file publish will not work on .NET 5. Binaries getting out-of-sync is a problem, but more of a theoretical one at this point. In the mentioned thread I don't think we knew of any recent times customers had a problem with binary mismatch.

If we think the proposed solution could be implemented in time for .NET 5, I have no problem with that. But if there's a chance that it will miss, I would propose we remove the check for now, and add a separate verification scheme later.

**Comment by hez2010** [comment]
Any updates on it?
I think unable to use WPF with PublishSingleFile is a critical problem.

**Comment by ryalanms** [comment]
@vatsan-madhavan, the updated version of the Verifier with more capabilities will need to be added back to .NET 6.  We need to take this for RC1.  Thanks.

**Comment by agocke** [comment]
@ryalanms It looks like this was merged into master. Is that the right branch for 5.0?

**Comment by ryalanms** [comment]
Yes, the intention is to bring this in to release/5.0, but there is an approval process required.  I'll merge it in when we get permission.  Thanks.

**Comment by agocke** [comment]
Any update on this? Is there an issue I can track for progress in Core Tactics?

**Pull request merged**
