### PR TITLE
Update to pool-provider sourced machines

### PR DESCRIPTION
**Pull request by MattGal**
@vatsan-madhavan FYI

### CODE REVIEW

**Comment by vatsan-madhavan** [comment]
I tried reading through https://github.com/dotnet/core-eng/issues/6288 but couldn't understand the differences between these pools. How are these pools different? 

This change would have to be made on https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-int and https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-test as well.

**Comment by MattGal** [comment]
@vatsan-madhavan the difference is basically that there was a time where we couldn't activate VS 2019 Preview SKUs (before RTM) so we needed to have vendors regularly log in and re-activate the machines, and the machines were a static set (so folks leaving leaked VS instances behind could only be manually cleaned up).  It's also a bit easier for us to update them to the latest preview builds (16.2 Preview 1 I believe as of today)

From a build perspective nothing should be changed;  it's up to @ilyas1974 as to how much longer that pool will persist though.

**Comment by ilyas1974** [comment]
@vatsan-madhavan, How long would you need us to keep the systems around to give you time to make the appropriate changes to your workloads? Also, what is the volume of workloads that are being run though these pools? Can we reduce the number of agents (currently their are 30 in the external pool and 10 in the internal pool)?

**Comment by vatsan-madhavan** [comment]
Now that we have forked off preview7 branch, we should figure this out now...

**Comment by vatsan-madhavan** [comment]
@MattGal, does this change need to be cherry-picked into release/3.0 branch? 

I'd prefer to not disrupt the release/3.0 branch at this time. If this chance must be made onto the release branch, can it wait until after a p6 build is finalized? 

/cc @mmitche

**Comment by MattGal** [comment]
@vatsan-madhavan it's fine to wait until P6 is ready to go; can you provide @ilyas1974 and myself with an ETA though?

**Comment by vatsan-madhavan** [comment]
@MattGal It all depends on when a coherent build is declared and we have test-signoffs and a release of p6 ready to ship - I'll be fine with porting over to release/3.0 immediately afterwards. 

Historically, it has happened within 1-2 week (i.e., likely this week or next week), but @mmitche  would be the best person to make that guess.

**Pull request merged**
