### PR TITLE
Fix QueryInsertEmbedded parameter type

### PR DESCRIPTION
**Pull request by kant2002**
## Description

Set proper parameter

## Customer Impact

Most likely nobody affected otherwise that should be crashing.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/wpf/pull/6622)

### CODE REVIEW

**Review by miloush — APPROVED** [review]
LGTM

**Comment by lindexi** [comment]
Yeah, the original code works well in X64 and X86

**Comment by miloush** [comment]
@lindexi how did you get it called?

**Comment by miloush** [comment]
@lindexi My LGTM was for the fix. Windows does not ship any TSF1 IME that can insert embedded objects and the method does not dereference the pointer anyway. While that might be "works well", it's still technically incorrect. I am happy for this PR to get merged, though it won't practically change anything and there isn't any functionality to test.

**Comment by lindexi** [comment]
@miloush LGTM. **While that might be "works well", it's still technically incorrect.**

**Review by dipeshmsft — APPROVED** [review]

**Review by dipeshmsft — APPROVED** [review]

**Comment by dipeshmsft** [comment]
@kant2002, this PR has been included in the current test pass. Will share the results once the test pass is complete.

**Pull request merged**
