### PR TITLE
Remove OleCmdHelper/ISecureCommand dead code (CAS/XBAP leftovers)

### PR DESCRIPTION
**Pull request by h3xds1nz**
## Description

Continues #9855 and #9865, removing even more XBAP related dead code (and some CAS related code).

- `OleCmdHelper` is uncalled, `CommandWithArgument` was only used in `OleCmdHelper`.
- `ISecureCommand` was also referenced via `OleCmdHelper` though it has been gutted out during CAS removal.
- `SecureUICommand` was created using `CommandLibraryHelper` on NetFX, removed during CAS removal too.

## Customer Impact

Smaller assembly size, improved code base quality for developers.

## Regression

No.

## Testing

Local build.

## Risk

I believe there is none, those classes are uncalled and interface unused since CAS removal.

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/wpf/pull/9943)

### CODE REVIEW

**Review by harshit7962 — DISMISSED** [review]
LGTM. 
@h3xds1nz, the PR can be merged post resolution of conflicts.

**Comment by h3xds1nz** [comment]
@harshit7962 Resolved.

**Review by harshit7962 — APPROVED** [review]
Reapproving after resolution of merge conflicts.

**Comment by harshit7962** [comment]
@h3xds1nz Thank you for your continued contributions.

**Comment by h3xds1nz** [comment]
@harshit7962 Thanks for iteratively working through them :)

**Pull request merged**
