### PR TITLE
Update branding to 8.0.2

### PR DESCRIPTION
**Pull request by vseanreesermsft**
null

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/wpf/pull/8625)

### CODE REVIEW

**Comment by harshit7962** [comment]
@mmitche -
 `error MSB4236: The SDK 'Microsoft.DotNet.Arcade.Sdk' specified could not be found.`
Seems like this is due to arcade version mismatch. Any inputs?

**Comment by singhashish-wpf** [comment]
Cc:// @dotnet/dnceng-admin

**Comment by mmitche** [comment]
> @mmitche - `error MSB4236: The SDK 'Microsoft.DotNet.Arcade.Sdk' specified could not be found.` Seems like this is due to arcade versions. Any inputs?

This was due to the AzDO outage yesterday

**Review by pchaurasia14 — APPROVED** [review]

**Pull request merged**
