### PR TITLE
[Cleanup] Use named arguments in System.Xaml

### PR DESCRIPTION
**Pull request by ThomasGoulet73**
Contributes to dotnet/wpf#10018

## Description
I replaced comments specifying an argument name with named arguments, which were introduced in C# 7. This improves readability and maintainability.

**Note: The compiled IL is identical.**

## Customer Impact
None.

## Regression
No.

## Testing
Local build + validated IL.

## Risk
Low to none.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/wpf/pull/10061)

### CODE REVIEW

**Review by lindexi — APPROVED** [review]
LGTM

**Review by himgoyalmicro — APPROVED** [review]

**Comment by himgoyalmicro** [comment]
LGTM. We have included it in test pass, and I will have the result soon.
Meanwhile, @ThomasGoulet73 Can you please resolve the merge conflicts?

**Comment by ThomasGoulet73** [comment]
Done.

**Review by himgoyalmicro — APPROVED** [review]

**Comment by himgoyalmicro** [comment]
Thank you @ThomasGoulet73 for your contribution 😄

**Comment by ThomasGoulet73** [comment]
Thanks

**Pull request merged**
