### PR TITLE
Include missing APIs in reference assembly

### PR DESCRIPTION
**Pull request by terrajobst**
It looks like these two APIs exist in the implementation and they also exist in the .NET Framework reference assemblies. This looks like an inadvertent omission to me.

Implementation links:

https://github.com/dotnet/wpf/blob/7511ae4c2e11d8eabb50a5ee9ee1b7c377b915fc/src/Microsoft.DotNet.Wpf/src/System.Windows.Controls.Ribbon/Microsoft/Windows/Controls/Ribbon/RibbonGalleryItem.cs#L102

https://github.com/dotnet/wpf/blob/7511ae4c2e11d8eabb50a5ee9ee1b7c377b915fc/src/Microsoft.DotNet.Wpf/src/System.Windows.Controls.Ribbon/Microsoft/Windows/Controls/Ribbon/RibbonGalleryItem.cs#L145

.NET Framework API documentation

* [RibbonGalleryItem.OnSelected](https://learn.microsoft.com/en-us/dotnet/api/system.windows.controls.ribbon.ribbongalleryitem.onselected?view=netframework-4.8)
* [RibbonGalleryItem.OnUnselected](https://learn.microsoft.com/en-us/dotnet/api/system.windows.controls.ribbon.ribbongalleryitem.onunselected?view=netframework-4.8)

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/wpf/pull/7168)

### CODE REVIEW

**Comment by miloush** [comment]
If you add them to the ref then you should remove them from the baseline.

**Comment by terrajobst** [comment]
@miloush done

**Comment by dipeshmsft** [comment]
@terrajobst, just wanted to know if you modified the ref assembly and the baseline files manually or using GenAPI ?

**Review by dipeshmsft — APPROVED** [review]

**Comment by terrajobst** [comment]
> @terrajobst, just wanted to know if you modified the ref assembly and the baseline files manually or using GenAPI ?

I believe manually

**Pull request merged**
