### PR TITLE
Fixup dependencies 

### PR DESCRIPTION
**Pull request by vatsan-madhavan**
- Update dependency Uri's to https://github.com/dotnet/runtime 
- Update CoherentParentDependency for packages coming from dotnet/runtime to Microsoft.Private.Winforms

### CODE REVIEW

**Comment by vatsan-madhavan** [comment]
> This doesn't update the URI's, but I _think_ Maestro will do that for you on the next update - @mmitche  can you confirm?

It's worse than that. Look at the two commits in this PR. I updated the Uri's manually to dotnet/runtime, and then updated dependencies. darc changed back dotnet/runtime -> dotnet/corefx etc.

**Comment by vatsan-madhavan** [comment]
I _think_ this may be the reason. 

WinForms has been semi-frozen to an older version of CoreFx/CoreCLR due to C++ tooling problems in dotnet/wpf. Those versions self-report as having been produced by dotnet/corefx etc, like this: 

```
λ darc get-asset --name Microsoft.NETCore.Platforms --version 5.0.0-alpha1.19512.1 --max-age 600
Looking up assets with name 'Microsoft.NETCore.Platforms' and version '5.0.0-alpha1.19512.1' in the last 600 days
Microsoft.NETCore.Platforms @ 5.0.0-alpha1.19512.1
Repository:    https://github.com/dotnet/corefx
Branch:        master
Commit:        8d21b79b924d29088dbde46d42737a657d466b5e
Build Number:  20191012.1
Date Produced: 10/12/2019 6:32 AM
Build Link:    https://dev.azure.com/dnceng/internal/_build/results?buildId=386333
BAR Build Id:  31220
Released:      False
Channels:
- .NET Core 5 Dev
Locations:
- https://dev.azure.com/dnceng/internal/_apis/build/builds/386333/artifacts (Container)
- https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json (NugetFeed)
- https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json (NugetFeed)
```

I would image that as we move over to newer versions, the repo Uri would get updated... right @mmitche ?

**Comment by wtgodbe** [comment]
> I would image that as we move over to newer versions, the repo Uri would get updated

That's right - This repo (intentionally) has the same version of Microsoft.Netcore.App.Internal as winforms, which is out of date. Once winforms gets up-to-date, so will this repo. You'll also need to fixup Winforms in the same way you fixed up this repo - Winforms still has CoreFx/CoreClr dependencies which list `Microsoft.Netcore.App.Internal` as a coherentParentDependency: https://github.com/dotnet/winforms/blob/e32620ed185e3c15fa67bdb7fe93757a735d6edb/eng/Version.Details.xml#L13-L15

**Comment by mmitche** [comment]
> > This doesn't update the URI's, but I _think_ Maestro will do that for you on the next update - @mmitche  can you confirm?
> 
> It's worse than that. Look at the two commits in this PR. I updated the Uri's manually to dotnet/runtime, and then updated dependencies. darc changed back dotnet/runtime -> dotnet/corefx etc.

It will. The isssue with update-dependencies is that there's no easy way to look up the latest of a giving asset on a channel without a source Uri.

**Pull request merged**
