### PR TITLE
update intellisense artifacts

### PR DESCRIPTION
**Pull request by AdamYoblick**
This PR is based on https://github.com/dotnet/winforms/pull/3999

### CODE REVIEW

**Comment by AdamYoblick** [comment]
Also, I searched for `DotNetApiDocsNetCoreApp30` in the wpf-int repo (https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-int?path=%2Fglobal.json&version=GBmaster&_a=contents) and I got no hits. So I don't think the `"dotnet-api-docs_netcoreapp3.0": "0.0.0.2"` specified in the global.json is used in that internal build.

Can someone from @dotnet/wpf-developers verify this please? If it's no longer used there, there's no work for me to do in that repo (and it should probably be removed from the global.json)

**Comment by AdamYoblick** [comment]
Also this PR is going into master. Once it gets in, it will need to be cherry-picked into the release/5.0-rc2 branch. I can do that as well once this gets merged.

**Review by fabiant3 — APPROVED** [review]

**Comment by AdamYoblick** [comment]
Hi @dotnet/wpf-developers - This PR build is failing but I don't know why. I see this same failure locally, but it has nothing to do with my changes. Can anyone assist here? Trying to get this change in before GA.

**Comment by vatsan-madhavan** [comment]
IIRC I reported this privately a few weeks ago as well as at https://github.com/dotnet/wpf/issues/3561#issuecomment-698012366. 

I gave up after spending a day-ish trying to fix this failure. I'm sure it can be solved with enough effort, I just don't have the time. Somebody from the team would likely have to spend time on it. There is something funny going on during NuGet restore  - could easily be a NuGet client bug.

**Comment by AdamYoblick** [comment]
Closing this in favor of https://github.com/dotnet/wpf/pull/3581

**Pull request closed without merging**
