### PR TITLE
Calling AppContext.TryGetSwitch without Reflection in LocalAppContext.cs

### PR DESCRIPTION
**Pull request by lindexi**
## Description

The AppContext.TryGetSwitch was a public method after .NET Framework 4.6 and we can call it without reflection.

https://docs.microsoft.com/en-us/dotnet/api/system.appcontext.trygetswitch?view=net-5.0

## Customer Impact

No need to call slow reflection when launching the app 

## Regression

.NET 7

## Testing

Just CI.

## Risk

Low. I do not change the behavior.

### CODE REVIEW

**Comment by lindexi** [comment]
@vishalmsft  Any update about the test result? Thank you.

**Comment by vishalmsft** [comment]
> @vishalmsft Any update about the test result? Thank you.
@lindexi we ran into few build issues. We are working on fixing it and take all the PR in November cycle.

**Comment by lindexi** [comment]
Thank you, @vishalmsft

**Review by singhashish-wpf — APPROVED** [review]

**Comment by lindexi** [comment]
Thank you @singhashish-wpf

**Pull request merged**
