### PR TITLE
Update OSVersionHelper.cs

### PR DESCRIPTION
**Pull request by meziantou**
Change `OperatingSystemVersion.Windows10RS3` to `OperatingSystemVersion.Windows10RS5`

### CODE REVIEW

**Comment by rladuca** [comment]
Yep, this is in both places.  GetOsVersion() is only used in error text for CompositeFont parsing, which basically never occurs, so that's why it never affected anything.

**Comment by ryalanms** [comment]
Good catch, @meziantou.

**Comment by vatsan-madhavan** [comment]
Historical note: 

When we added these checks a few years ago, `RtlVerifyVersionInfo` was only exposed through the DDK headers - it was not documented as an entrypoint in `ntdll.dll`. So we consumed it in our native layer (`PresentationNative`, I think), and P/Invoked into our native DLL's from managed code. This is the current design.

Over the years, `RtlVerifyVersionInfo` has since been documented as being available as a user-mode entrypoint  [in `ntdll.dll`](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-rtlverifyversioninfo), which means that we can P/Invoke directly into `ntdll` now. 

[We only consume Win32 API's that are public and documented in WPF]

**Comment by vatsan-madhavan** [comment]
@meziantou, thanks for the catch and the patch!

**Pull request merged**
