### PR TITLE
avoid boxing for xxxAnimationUsingKeyFrames

### PR DESCRIPTION
**Pull request by NaBian**

### CODE REVIEW

**Comment by stevenbrix** [comment]
@NaBian thank you for sending out this PR. Can you provide a little more information on what benefit this PR has?

**Comment by oysteinkrog** [comment]
This is a nice improvement, it prevents some allocations in a core component, in our large application I see allocations in these lines when animations/storyboards are running.

**Review by dipeshmsft — APPROVED** [review]

**Comment by dipeshmsft** [comment]
@NaBian, thank for your contribution. Sorry for the time it took to get this PR merged.

**Pull request merged**
