### PR TITLE
Update .NET 5 templates with net5.0 tfm

### PR DESCRIPTION
**Pull request by grinrag**
SDK related issue https://github.com/dotnet/sdk/issues/11706

### CODE REVIEW

**Comment by mmitche** [comment]
@ViktorHofer was this supposed to be for p5?

**Comment by ViktorHofer** [comment]
If it's not too late for P5 then ideally yes otherwise P6 is fine as well.

**Comment by mmitche** [comment]
We'll discuss in tactics today. Can you prepare porting PRs?

**Comment by ViktorHofer** [comment]
Sure.

**Pull request merged**
