### PR TITLE
Clean-up `Microsoft.WinFX.targets` file

### PR DESCRIPTION
**Pull request by Nirmal4G**
- Fixup new-lines
- Remove trailing white-space
- Respect EditorConfig preferences

### CODE REVIEW

**Comment by Nirmal4G** [comment]
@ryalanms @dsplaisted 🔔

**Comment by Nirmal4G** [comment]
@ryalanms @vatsan-madhavan 🔔

**Comment by Nirmal4G** [comment]
This is fairly a simple one, I think! 🤔

So, can someone/anyone (_please_) take a look at this patch at priority? 🧐

**Review by ryalanms — APPROVED** [review]

**Comment by ryalanms** [comment]
The 6.0 branch is closed for check-ins.  This needs to go in to 7.0 (main).

**Comment by Nirmal4G** [comment]
@ryalanms Rebase done. This is fairly a non-breaking/no-code-change patch, why it didn't qualify for v6 branch?

**Comment by Nirmal4G** [comment]
@ryalanms 🔔

**Comment by ryalanms** [comment]
Thanks, @Nirmal4G.  Nothing is going in to 6.0 at this stage other than a small set of pre-approved changes (Intellisense, localization, etc.)

**Pull request merged**
