### PR TITLE
Add SDL vars config file

### PR DESCRIPTION
**Pull request by mmitche**
Enables post-build and nightly SDL verification, rather than within the build

### CODE REVIEW

**Comment by vatsan-madhavan** [comment]
hmm.. these values used to come from a variable group.

**Comment by rladuca** [comment]
> hmm.. these values used to come from a variable group.

Also, if these are different values (path wise) isn't that going to create noise with re-filed TSA bugs?

**Comment by mmitche** [comment]
They're the same values as those from the variable group, with the exception that @vatsan-madhavan's alias got updated to fabiant's

**Comment by mmitche** [comment]
> hmm.. these values used to come from a variable group.

That was only possible because the values were referenced from the yaml.

**Pull request merged**
