### PR TITLE
In ClrObjectRuntime, move the object definition next to the code used

### PR DESCRIPTION
**Pull request by lindexi**
Only in exceptions do we need to use string splicing logic, which means that this string splicing code is wasteful in normal use

### CODE REVIEW

**Comment by dipeshmsft** [comment]
Hey @lindexi, does this PR have any performance implications? Any kind of improvement?

**Comment by lindexi** [comment]
@dipeshmsft Yes, normally, we don't need to alloc memory for qMethodName.

**Review by dipeshmsft — APPROVED** [review]

**Comment by dipeshmsft** [comment]
Hey @lindexi, we are ready to take this PR. Can you go ahead and resolve the conflicts? Thanks a lot for your continued support.

**Comment by lindexi** [comment]
Thank you @dipeshmsft 

And I will fix it soon.

**Comment by dipeshmsft** [comment]
Thanks @lindexi for your contribution and quick response.

**Pull request merged**
