### PR TITLE
111

### PR DESCRIPTION
**Pull request by sdcarterchen**

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/wpf?pullRequest=3139) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/wpf?pullRequest=3139) before we can accept your contribution.<br/><br/>:x: sdcarterchen [sign now](https://cla.dotnetfoundation.org/dotnet/wpf?pullRequest=3139)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/wpf?pullRequest=3139) it.</sub>

**Comment by lindexi** [comment]
@sdcarterchen Do you want to publish the private version wpf?

See https://github.com/dotnet-campus/wpf/pull/1

**Comment by ryalanms** [comment]
Hi, @sdcarterchen.  Can you close this PR?  Thanks.

**Comment by ryalanms** [comment]
Thanks for the PR, @sdcarterchen.  We need more detail as to what was intended, so I'm closing this for now.

**Pull request closed without merging**
