### PR TITLE
Community.testpass.1.25.2021

### PR DESCRIPTION
**Pull request by ryalanms**
**Community PR Test Pass 1/25/2021**

These PRs will be merged if no regressions are found.

**Community PRs included in this test branch:**

@lindexi: 

Using array empty to replace create an empty array #2843

@GrabYourPitchforks: 

Remove custom copy of PtrToStringChars #3117

@benaadams: 

Use char.{Last}IndexOf #3285

@ThomasGoulet73: 

Use char overload in System.Xaml #3998

@lindex:  

Use readonly struct in System.Windows.Input.Manipulations.PointF #4017 

**Test Matrix**

| OS | Architecture |
| --- | --- |
| Windows 7 SP1	Enterprise	| x86 |	
| Windows 7 SP1	Enterprise	| x64 |	
| Windows Blue	Enterprise	| x86 |	
| Windows Server 2012 R2 SP1	| x64 |
| Win10 RS1                	Enterprise	| x86 |
| Win10 RS3	Enterprise	| x64 |
| Win10 RS4	Enterprise	| x86 |
| Windows Server 2019		| x64  |
| Win10 RS6	Enterprise	| X86 |
| Windows Server 2016	 | x64 |

### CODE REVIEW

**Comment by ryalanms** [comment]
These PRs need to be merged individually.  Do not merge this Community Test Pass PR directly.

**Comment by ryalanms** [comment]
Two separate PRs added an IndexOf method to KnownStrings.cs. 

+        /// <summary>
+        /// Standard String Index search operation.
+        /// </summary>
+        public static int IndexOf(string src, char ch)
+        {
+            return src.IndexOf(ch, StringComparison.Ordinal);
+        }
+

**Comment by ryalanms** [comment]
Thanks everyone.  There was an additional AppModel failure in the test pass results that had to be investigated before these could be merged.

**Comment by ryalanms** [comment]
(The individual PRs are merged individually.  This will be closed.)

**Comment by ThomasGoulet73** [comment]
> Two separate PRs added an IndexOf method to KnownStrings.cs.
> 
> ```cs
>         /// <summary>
>         /// Standard String Index search operation.
>         /// </summary>
>         public static int IndexOf(string src, char ch)
>         {
>             return src.IndexOf(ch, StringComparison.Ordinal);
>         }
> ```

@ryalanms I don't think this was fixed. There appear to be two methods with the same parameters but with a slightly different content: https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/MS/Impl/KnownStrings.cs.  If you want, I could open a PR later today to remove one of the duplicate method.

**Comment by ryalanms** [comment]
@thomasclaudiushuber:  Thanks for catching that.  I fixed it when merging everything in to the community test pass branch, but not in master.

**Pull request closed without merging**
