### PR TITLE
FindCommandBinding improvements

### PR DESCRIPTION
**Pull request by deeprobin**
Might fix Issue #4869

## Description

The main focus was on the FindCommandBinding method in CommandManager.cs. Here I decided to use a ValueTuple instead of a Tuple as well as to do the check using a switch-is block, as this is most likely easier to optimize through the JIT.

Furthermore, I made other code improvements in related methods, like reducing code-nesting and using new C# features.

I don't think these make a big difference to the generated JIT asm, but still hope to have made the code a bit more readable.

/cc @IAmTheCShark

### CODE REVIEW

**Comment by IAmTheCShark** [comment]
I do not believe this fixes #4869 because the algorith itself is quite inefficient to my understanding.
Looking at your changes those are mosly refactorings in favour of new language features. Or did I miss something?

**Comment by deeprobin** [comment]
> 
> 
> I do not believe this fixes #4869 because the algorithm itself is quite inefficient to my understanding. Looking at your changes those are mosly refactorings in favour of new language features. Or did I miss something?

The usage of ValueTuples instead of Tuples might improve the performance a little bit. But I don't know how to benchmark WPF Code because BenchmarkDotNet does not work with this workset

**Comment by lindexi** [comment]
> BenchmarkDotNet

See https://github.com/dotnet/BenchmarkDotNet/issues/1616

**Review by anjalisheel-wpf — APPROVED** [review]

**Comment by deeprobin** [comment]
@anjalisheel-wpf What is the current status on this?

**Comment by anjalisheel-wpf** [comment]
@deeprobin we ran into .NET 7 migration issues. So, taking time to merge community test pass this month.

**Pull request merged**
