### PR TITLE
Add the demo to debug.

### PR DESCRIPTION
**Pull request by lindexi**
## Description

How about adding a demo project to help us debug more easily?

## Testing

Just CI.

## Risk

Low.

### CODE REVIEW

**Comment by vishalmsft** [comment]
@lindexi The demo is to help with setting up debugging environment faster. 
While debugging, people will be modify the demo to debug various features. 
Do you think it will cause unnecessary commits of files?

Even if we use demo, do you think it may be good idea to copy the project to output-temp directory, which shall be ignored from commits?

**Comment by lindexi** [comment]
@vishalmsft  Good ideas.

**Comment by dipeshmsft** [comment]
@lindexi Should we go ahead and close this PR ??

**Comment by lindexi** [comment]
@dipeshmsft Yes.

**Pull request closed without merging**
