### PR TITLE
Workaround missing lib with non-preview images

### PR DESCRIPTION
**Pull request by mmitche**
Should work around https://github.com/dotnet/arcade/issues/10106

### CODE REVIEW

**Comment by mmitche** [comment]
Test build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1905250&view=results

**Comment by mmitche** [comment]
@singhashish-wpf Can you take a look at this to unblock p7 when you get a chance, and merge?

**Comment by dkurepa** [comment]
the jobs are run on the windows-2019 which has the vs2019 installed on them, I think we need to change this to windows-2022

**Comment by dkurepa** [comment]
looks like it was a an AzDo bug, the runs are using the correct images now

**Review by dkurepa — APPROVED** [review]

**Pull request merged**
