### PR TITLE
Adding Stable Branding .NET 8 RTM

### PR DESCRIPTION
**Pull request by harshit7962**
## Description
Adding StabilizePackageVersion tag to enable stable branding.

## Testing
Local build pass

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/wpf/pull/8338)

### CODE REVIEW

**Comment by Kuldeep-MS** [comment]
@harshit7962 - can you please add more details, why the change is required also attach any issue if it exists.

**Review by Kuldeep-MS — APPROVED** [review]
As discussed, changes look good to me.

**Comment by dkurepa** [comment]
I don't think this change is needed, since WPF doesn't have any shipping packages.
Has something changed, do we construct some shipping packages in wpf now?

**Review by dkurepa — CHANGES_REQUESTED** [review]
I don't think this change is needed, since WPF doesn't have any shipping packages.
Has something changed, do we construct some shipping packages in wpf now?

**Comment by singhashish-wpf** [comment]
We don't produced shipping packages. This happened before confirmation. Closing the PR.

**Pull request closed without merging**
