### PR TITLE
Add NoTestFileCreate property in FileDialog

### PR DESCRIPTION
**Pull request by lindexi**
Fix https://github.com/dotnet/wpf/issues/870

I don’t know if this property is appropriate

### CODE REVIEW

**Review by ryalanms — CHANGES_REQUESTED** [review]
Please make summary formatting consistent with the rest of the file, and consider updating this property to `TestFileCreate` similar to `DereferenceLinks`.

**Comment by ryalanms** [comment]
Although this is a minor modification, it is a public API change and requires an API review.

**Comment by miloush** [comment]
I would suggest the name to be reconsidered. A similar property, `OFN_NODEREFERENCELINKS` is represented by `DereferenceLinks` so `OFN_NOTESTFILECREATE` should follow the suite, perhaps as `CreateTestFile` or similar.

**Comment by lindexi** [comment]
@ryalanms @miloush  Thank you. How about `ShouldCreateTestFile` ?

**Comment by ryalanms** [comment]
Adding @MikeHillberg for API review...

**Comment by dipeshmsft** [comment]
@lindexi, since the corresponding PR #7916 has been merged for this, I am closing this PR. Nevertheless, thanks for your efforts. We hope to see more contributions from you in the future.

**Comment by lindexi** [comment]
Thank you @dipeshmsft

**Pull request closed without merging**
