### PR TITLE
Make TemplatedAdorner public

### LINKED ISSUE #236: Make TemplatedAdorner public.
It is a useful type.

### PR DESCRIPTION
**Pull request by AllanRegush**
Fixes #236

## Description
This PR makes a change in api to make TemplatedAdorner public

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/wpf/pull/6938)

### CODE REVIEW

**Comment by lindexi** [comment]
@AllanRegush To fix the CI, you should update the API Compatibility file. See https://github.com/dotnet/wpf/blob/main/Documentation/api-compat.md and https://github.com/dotnet/wpf/blob/main/Documentation/gen-api.md

**Comment by AllanRegush** [comment]
> @AllanRegush Thank you. To fix the CI, you should update the API Compatibility file. See https://github.com/dotnet/wpf/blob/main/Documentation/api-compat.md and https://github.com/dotnet/wpf/blob/main/Documentation/gen-api.md

Hello,

I've read over the documentation.

For clarification, are you wanting me to run set BaselineAllAPICompatError to true on build and commit the updated `src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/PresentationFramework-ref.baseline.txt`? Or, do I set `/p:GenerateReferenceAssemblySource=true` on build? 

Thank you.

**Comment by AllanRegush** [comment]
Hi There.

I noticed there is some activity on this PR.

Has anyone had time to answer my question?

>For clarification, are you wanting me to run set BaselineAllAPICompatError to true on build and commit the updated `src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/PresentationFramework-ref.baseline.txt`? Or, do I set /p:GenerateReferenceAssemblySource=true on build?

I can commit the updated file and the PR will pass CI. Just wanted clarification on if that is correct.

Thanks,

Allan

**Comment by batzen** [comment]
While i agree that this type, or better said parts of it, are useful.
I think it's not a good idea to make types from the namespace `MS.Internal.Controls` public and keep that namespace.
Also, i don't think that people trying to use this class will be aware that the `DataContext` is forced to be `Validation.GetErrors(adornedElement)`.

I guess the best solution would be to move the class to a different namespace.
Remove the forced datacontext.
Create a derived class that forces the datacontext for validation or set the datacontext in a different way at the callers side (by getting the visual child and setting it's datacontext for example).

**Comment by AllanRegush** [comment]
Closing PR. I won't be able to get back to this.  Someone else should have a go.

**Pull request closed without merging**
