### PR TITLE
Merge internal/release/5.0 to release/5.0 and update branding

### PR DESCRIPTION
**Pull request by ryalanms**
FYI, the internal feeds in nuget.config are intentional and benign.  Thanks.

### CODE REVIEW

**Comment by ryalanms** [comment]
The non-shipping packages are still being pushed to the public transport feed.  This will fail until dependencies are available.

**Comment by RussKie** [comment]
> The non-shipping packages are still being pushed to the public transport feed. This will fail until dependencies are available.

I had a quick chat with @mmitche, and he said it's been worked on.
/cc: @wtgodbe

**Comment by ryalanms** [comment]
The CI build is passing now.  I'll merge when it completes.

**Pull request merged**
